version: "3"

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - telegram_token=${telegram_token}
    volumes:
      - unidata:/localdata
   
    restart: always
volumes:
  unidata:
    driver: local
    driver_opts:
      type: none
      device: /home/haytham/ML/Pyscrpt/unidata
      o: bind